micronaut:
  application:
    name: keymanager

grpc:
  server:
    port: 50051
    keep-alive-time: 3h
    max-inbound-message-size: 1024

datasources:
  default:
    url: jdbc:h2:mem:keymanager;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: root
    password: 'root'
    schema-generate: CREATE_DROP
    dialect: H2

jpa:
  default:
    entity-scan:
      packages: 'com.orange.keymanager.models'

jackson:
  serializationInclusion: ALWAYS